### ISSUE TITLE
Light Portable Wood Fired Generator - Output problem

### ISSUE THREAD

**Issue by flatline4400** [emipa606/CaravanEquipment#1]
The item when deployed *requires* 750W.  Thus it doesn't work.

It's defined properly in the CE_Buildings_Power.xml with a negative value.  However, this appears to  get overwritten by the value in the Mod Options screen, which defaults to *positive* 750, and you cant input a negative number into that field.  Because of this, instead of providing power, it sucks it up!

I assume the issue is baked into the .dll, since I couldnt find anywhere to change that behaviour in the other files.

**Comment by emipa606** [comment]
Should be fixed in b1c0701
Thanks for reporting!

**Comment by flatline4400** [comment]
Thanks for the quick fix!!
